In [1]:
import numpy as np

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

#Print out array
my_array1

array([1, 2, 3, 4])

In [2]:
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [3]:
my_array2.shape

(2, 4)

In [4]:
my_array2.shape[0]

2

In [5]:
my_array2.shape[1]

4

In [6]:
my_array2.dtype

dtype('int64')

In [7]:
np.empty(5)


array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
np.empty((3,4))


array([[  0.00000000e+000,  -4.33712388e-311,   2.96439388e-323,
          4.94065646e-324],
       [  0.00000000e+000,   2.46567264e+179,   0.00000000e+000,
          2.52699646e-052],
       [  0.00000000e+000,   1.09689445e-071,   0.00000000e+000,
          8.34402697e-309]])

In [9]:
np.zeros(5)


array([ 0.,  0.,  0.,  0.,  0.])

In [10]:
np.ones((5,5))


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.eye(5)


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [12]:
np.arange(5)


array([0, 1, 2, 3, 4])